#ifndef ARM_TRUSTED_FIRMWARE_EXPORT_TRUSTLEECH_EXP_H
#define ARM_TRUSTED_FIRMWARE_EXPORT_TRUSTLEECH_EXP_H

/* 32MiB are reserved in the DTB */
#define TRUSTLEECH_AREA_SIZE 0x3000000

#define TRUSTLEECH_MAX_CORES 4

/* The reserved 32MiB lie 3GiB into the physical address space (which is 1GiB into DRAM) */
#define TRUSTLEECH_BASE 0xC0000000
#define TRUSTLEECH_SIZE 0x3000000
#define TRUSTLEECH_LIMIT (TRUSTLEECH_BASE + TRUSTLEECH_SIZE)

/* The 1MiB text section lies at the beginning of the executable */
#define TRUSTLEECH_TEXT_BASE (TRUSTLEECH_BASE)
#define TRUSTLEECH_TEXT_SIZE 0x100000
#define TRUSTLEECH_TEXT_LIMIT (TRUSTLEECH_TEXT_BASE + TRUSTLEECH_TEXT_SIZE)

#define TRUSTLEECH_ENTRYPOINT (TRUSTLEECH_TEXT_BASE)

/* Context is saved in a 64KiB array starting 1MiB after the TRUSTLEECH_BASE */
#define TRUSTLEECH_CONTEXT_STASH_BASE (TRUSTLEECH_TEXT_LIMIT)
#define TRUSTLEECH_CONTEXT_STASH_SIZE 0x10000
#define TRUSTLEECH_CONTEXT_STASH_LIMIT (TRUSTLEECH_CONTEXT_STASH_BASE + TRUSTLEECH_CONTEXT_STASH_SIZE)

/* 128KiB Stack per core */
#define TRUSTLEECH_SINGLE_STACK_SIZE 0x20000
#define TRUSTLEECH_STACKS_BASE (TRUSTLEECH_CONTEXT_STASH_LIMIT)
#define TRUSTLEECH_STACKS_SIZE (TRUSTLEECH_MAX_CORES * TRUSTLEECH_SINGLE_STACK_SIZE)
#define TRUSTLEECH_STACKS_LIMIT (TRUSTLEECH_STACKS_BASE + TRUSTLEECH_STACKS_SIZE)
#define TRUSTLEECH_STACKS_INT_BASE (TRUSTLEECH_STACKS_LIMIT)
#define TRUSTLEECH_STACKS_INT_LIMIT (TRUSTLEECH_STACKS_INT_BASE + TRUSTLEECH_STACKS_SIZE)

/* 2MiB should be enough room for read only data */
#define TRUSTLEECH_RODATA_BASE (TRUSTLEECH_STACKS_INT_LIMIT)
#define TRUSTLEECH_RODATA_SIZE 0x200000
#define TRUSTLEECH_RODATA_LIMIT (TRUSTLEECH_RODATA_BASE + TRUSTLEECH_RODATA_SIZE)

#define TRUSTLEECH_RWDATA_BASE (TRUSTLEECH_RODATA_LIMIT)
#define TRUSTLEECH_RWDATA_LIMIT (TRUSTLEECH_LIMIT)

/** QEMU reserves the bottom 1GiB of the physical address space for MMIO, and we use 4GiB of DRAM on
 * top of that
 */
#define TRUSTLEECH_PLAT_RAM_LIMIT 0x140000000

#define TRUSTLEECH_PCI_BASE 0x4000000000
#define TRUSTLEECH_PCI_LIMIT 0x4020000000

#define TRUSTLEECH_DMA_BASE 0x8000000000
#define TRUSTLEECH_DMA_LIMIT 0x8020000000
#endif /* ARM_TRUSTED_FIRMWARE_EXPORT_TRUSTLEECH_EXP_H */
